var result = [{
    RECEIVEREMAIL: 'david.p@casamiento-cards.co.uk',
    RECEIVERID: '4WWJ2HESU6USU',
    EMAIL: 'horse.shit@bigpond.com',
    PAYERID: 'T5TYQARXUZ4PE',
    PAYERSTATUS: 'verified',
    COUNTRYCODE: 'AU',
    SHIPTONAME: 'Peter Paisley',
    SHIPTOSTREET: '737 South Dowling St',
    SHIPTOCITY: 'Redfern',
    SHIPTOSTATE: 'New South Wales',
    SHIPTOCOUNTRYCODE: 'AU',
    SHIPTOCOUNTRYNAME: 'Australia',
    SHIPTOZIP: '2016',
    ADDRESSOWNER: 'PayPal',
    ADDRESSSTATUS: 'Unconfirmed',
    SALESTAX: '0.00',
    SHIPDISCOUNT: '0.00',
    INSURANCEAMOUNT: '0.00',
    BUYERID: 'peterp6166',
    CLOSINGDATE: '2012-04-15T16:19:49Z',
    MULTIITEM: '5',
    TIMESTAMP: '2012-07-30T21:33:24Z',
    CORRELATIONID: '9cd5817281a5d',
    ACK: 'Success',
    VERSION: '86.0',
    BUILD: '3386080',
    FIRSTNAME: 'Peter',
    LASTNAME: 'Paisley',
    TRANSACTIONID: '4UB99755043781212',
    TRANSACTIONTYPE: 'cart',
    PAYMENTTYPE: 'instant',
    ORDERTIME: '2012-04-16T05:48:11Z',
    AMT: '73.61',
    FEEAMT: '3.81',
    TAXAMT: '0.00',
    SHIPPINGAMT: '9.73',
    HANDLINGAMT: '0.00',
    CURRENCYCODE: 'GBP',
    PAYMENTSTATUS: 'Completed',
    PENDINGREASON: 'None',
    REASONCODE: 'None',
    SHIPPINGMETHOD: 'Default',
    PROTECTIONELIGIBILITY: 'Eligible',
    PROTECTIONELIGIBILITYTYPE: 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    L_EBAYITEMTXNID0: '0',
    L_EBAYITEMTXNID1: '0',
    L_EBAYITEMTXNID2: '0',
    L_EBAYITEMTXNID3: '0',
    L_EBAYITEMTXNID4: '0',
    L_NAME0: 'Antique Microscope Slide Foot of Gyrinus Natator, Smith Beck & Beck',
    L_NAME1: 'Antique Microscope Slide Foot of Soldier Beetle, Smith Beck & Beck',
    L_NAME2: 'Antique Microscope Slide Head of Female Gnat, Smith Beck & Beck',
    L_NAME3: 'Antique Microscope Slide Calcedony Polariscope Smith Beck & Beck',
    L_NAME4: 'Antique Microscope Slide Horn Of Rhinosceros Polaricope Smith Beck & Beck',
    L_NUMBER0: '260997821242',
    L_NUMBER1: '251035046042',
    L_NUMBER2: '251035043931',
    L_NUMBER3: '251035041844',
    L_NUMBER4: '251035040824',
    L_QTY0: '1',
    L_QTY1: '1',
    L_QTY2: '1',
    L_QTY3: '1',
    L_QTY4: '1',
    L_TAXAMT0: '0.00',
    L_TAXAMT1: '0.00',
    L_TAXAMT2: '0.00',
    L_TAXAMT3: '0.00',
    L_TAXAMT4: '0.00',
    L_SHIPPINGAMT0: '0.00',
    L_SHIPPINGAMT1: '0.00',
    L_SHIPPINGAMT2: '0.00',
    L_SHIPPINGAMT3: '0.00',
    L_SHIPPINGAMT4: '0.00',
    L_HANDLINGAMT0: '0.00',
    L_HANDLINGAMT1: '0.00',
    L_HANDLINGAMT2: '0.00',
    L_HANDLINGAMT3: '0.00',
    L_HANDLINGAMT4: '0.00',
    L_CURRENCYCODE0: 'GBP',
    L_CURRENCYCODE1: 'GBP',
    L_CURRENCYCODE2: 'GBP',
    L_CURRENCYCODE3: 'GBP',
    L_CURRENCYCODE4: 'GBP',
    L_AMT0: '4.21',
    L_AMT1: '3.20',
    L_AMT2: '4.21',
    L_AMT3: '24.26',
    L_AMT4: '28.00'
}, {
    RECEIVERBUSINESS: 'paypal@dizzy.co.uk',
    RECEIVEREMAIL: 'david.p@casamiento-cards.co.uk',
    RECEIVERID: '4WWJ2HESU6USU',
    EMAIL: 'dpoore3@att.net',
    PAYERID: 'P8MGUX5VKH5X2',
    PAYERSTATUS: 'verified',
    COUNTRYCODE: 'US',
    SHIPTONAME: 'Dennis Poore',
    SHIPTOSTREET: '1043 Diamond Dr',
    SHIPTOCITY: 'Arcata',
    SHIPTOSTATE: 'CA',
    SHIPTOCOUNTRYCODE: 'US',
    SHIPTOCOUNTRYNAME: 'United States',
    SHIPTOZIP: '95521-8349',
    ADDRESSOWNER: 'PayPal',
    ADDRESSSTATUS: 'Confirmed',
    SALESTAX: '0.00',
    SHIPDISCOUNT: '0.00',
    INSURANCEAMOUNT: '0.00',
    BUYERID: 'hexapod2',
    CLOSINGDATE: '2012-04-15T14:17:55Z',
    TIMESTAMP: '2012-07-30T21:33:24Z',
    CORRELATIONID: '7374199298903',
    ACK: 'Success',
    VERSION: '86.0',
    BUILD: '3386080',
    FIRSTNAME: 'DENNIS',
    LASTNAME: 'POORE',
    TRANSACTIONID: '41B12534U9229032P',
    TRANSACTIONTYPE: 'cart',
    PAYMENTTYPE: 'instant',
    ORDERTIME: '2012-04-15T21:55:03Z',
    AMT: '7.11',
    FEEAMT: '0.48',
    TAXAMT: '0.00',
    SHIPPINGAMT: '2.10',
    HANDLINGAMT: '0.00',
    CURRENCYCODE: 'GBP',
    PAYMENTSTATUS: 'Completed',
    PENDINGREASON: 'None',
    REASONCODE: 'None',
    SHIPPINGMETHOD: 'Default',
    PROTECTIONELIGIBILITY: 'Eligible',
    PROTECTIONELIGIBILITYTYPE: 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    L_EBAYITEMTXNID0: '0',
    L_NAME0: 'Antique Microscope Slide Sarcoma, R & J Beck',
    L_NUMBER0: '251035042580',
    L_QTY0: '1',
    L_TAXAMT0: '0.00',
    L_SHIPPINGAMT0: '0.00',
    L_HANDLINGAMT0: '0.00',
    L_CURRENCYCODE0: 'GBP',
    L_AMT0: '5.01'
}, {
    RECEIVERBUSINESS: 'paypal@dizzy.co.uk',
    RECEIVEREMAIL: 'david.p@casamiento-cards.co.uk',
    RECEIVERID: '4WWJ2HESU6USU',
    EMAIL: 'heather975@btinternet.com',
    PAYERID: '376PFXCB8VMBC',
    PAYERSTATUS: 'verified',
    COUNTRYCODE: 'GB',
    SHIPTONAME: 'Gareth Bryan',
    SHIPTOSTREET: 'Graig Cottage, Old School Lane,',
    SHIPTOSTREET2: 'Eryrys,',
    SHIPTOCITY: 'Mold',
    SHIPTOSTATE: 'Denbighshire',
    SHIPTOCOUNTRYCODE: 'GB',
    SHIPTOCOUNTRYNAME: 'United Kingdom',
    SHIPTOZIP: 'CH7 4DA',
    ADDRESSOWNER: 'PayPal',
    ADDRESSSTATUS: 'Confirmed',
    SALESTAX: '0.00',
    SHIPDISCOUNT: '0.00',
    INSURANCEAMOUNT: '0.00',
    BUYERID: '6461gareth',
    CLOSINGDATE: '2012-04-15T14:21:51Z',
    TIMESTAMP: '2012-07-30T21:33:25Z',
    CORRELATIONID: 'b77f5754ab248',
    ACK: 'Success',
    VERSION: '86.0',
    BUILD: '3386080',
    FIRSTNAME: 'Gareth',
    LASTNAME: 'Bryan',
    TRANSACTIONID: '95G39778N81454512',
    TRANSACTIONTYPE: 'cart',
    PAYMENTTYPE: 'instant',
    ORDERTIME: '2012-04-15T21:33:34Z',
    AMT: '5.61',
    FEEAMT: '0.39',
    TAXAMT: '0.00',
    SHIPPINGAMT: '1.40',
    HANDLINGAMT: '0.00',
    CURRENCYCODE: 'GBP',
    PAYMENTSTATUS: 'Completed',
    PENDINGREASON: 'None',
    REASONCODE: 'None',
    SHIPPINGMETHOD: 'Default',
    PROTECTIONELIGIBILITY: 'Eligible',
    PROTECTIONELIGIBILITYTYPE: 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    L_EBAYITEMTXNID0: '0',
    L_NAME0: 'Antique Microscope Slide Foot of Spider, Smith Beck & Beck',
    L_NUMBER0: '251035045087',
    L_QTY0: '1',
    L_TAXAMT0: '0.00',
    L_SHIPPINGAMT0: '0.00',
    L_HANDLINGAMT0: '0.00',
    L_CURRENCYCODE0: 'GBP',
    L_AMT0: '4.21'
}]
var result = result[0]
var objects = []
var parsedResult = {}
for (var key in result) {
    if (isNaN((key[key.length - 1] / 1))) {
        parsedResult[key] = result[key]
    }
    else {
        var matches = key.match(/(\d+)$/)
        var id = matches[0];
        objects[id] = objects[id] || {}
        var truncatedKey = key.substring(0, key.length - id.length);
        objects[id][truncatedKey] = result[key];
    }
}
console.log("DONE");
console.log(parsedResult);